version: '3.8'

services:
  frontend:
    container_name: lish-frontend-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: lish/frontend-app
    ports:
      - "80:80"
    networks:
      - container-link

networks:
  default:
    external:
      name: bridge
  container-link:
    name: lish.docker.internal
