version: '3.8'

services:
  frontend:
    container_name: lish-frontend-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: dev
    image: lish/frontend-app
    ports:
      - "5431:3000"
    networks:
      - container-link
    volumes:
      - ./app:/app:rw
      - /app/node_modules

networks:
  default:
    name: bridge
  container-link:
    name: lish.docker.internal
